name: Run Partial Script

on:
  workflow_dispatch:
    inputs:
      script:
        description: 'Çalıştırılacak script (ör: scripts/update_pois.py)'
        required: true
        type: choice
        options:
          - scripts/update_pois.py
          - scripts/generate_sf_crime_52.py
          - scripts/update_311.py
          - scripts/update_911.py
          - scripts/update_poi.py
      args:
        description: 'İsteğe bağlı argümanlar (ör: --in data.csv --out out.csv)'
        required: false
        default: ''

permissions:
  contents: read

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies (if any)
        run: |
          python -m pip install -U pip wheel setuptools
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Run chosen script
        run: |
          echo "▶ ${ { github.event.inputs.script } } ${ { github.event.inputs.args } }"
          python "${{ github.event.inputs.script }}" ${{ github.event.inputs.args }}
